// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq5ej6qGaRgTgT_rZSxCcIINszl_9O_mw',
    appId: '1:1088862155716:web:6129b18753c4c711a0ea91',
    messagingSenderId: '1088862155716',
    projectId: 'fir-app-abf52',
    authDomain: 'fir-app-abf52.firebaseapp.com',
    storageBucket: 'fir-app-abf52.firebasestorage.app',
    measurementId: 'G-GSJNE73F2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZo31EG-WRMXbzCb2J-TLyjkNEDi2WU9U',
    appId: '1:1088862155716:android:e6e8f4b6db518519a0ea91',
    messagingSenderId: '1088862155716',
    projectId: 'fir-app-abf52',
    storageBucket: 'fir-app-abf52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj8EfeK_TLzysnTE_NorU4CElOuGJOVzE',
    appId: '1:1088862155716:ios:6b9d23e17bd83bf3a0ea91',
    messagingSenderId: '1088862155716',
    projectId: 'fir-app-abf52',
    storageBucket: 'fir-app-abf52.firebasestorage.app',
    iosBundleId: 'com.example.doctorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj8EfeK_TLzysnTE_NorU4CElOuGJOVzE',
    appId: '1:1088862155716:ios:6b9d23e17bd83bf3a0ea91',
    messagingSenderId: '1088862155716',
    projectId: 'fir-app-abf52',
    storageBucket: 'fir-app-abf52.firebasestorage.app',
    iosBundleId: 'com.example.doctorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq5ej6qGaRgTgT_rZSxCcIINszl_9O_mw',
    appId: '1:1088862155716:web:1998c861b289aca3a0ea91',
    messagingSenderId: '1088862155716',
    projectId: 'fir-app-abf52',
    authDomain: 'fir-app-abf52.firebaseapp.com',
    storageBucket: 'fir-app-abf52.firebasestorage.app',
    measurementId: 'G-W2CP18KHVD',
  );
}
